### ISSUE TITLE
`fetch` is not defined

### ISSUE THREAD

**Issue by vimwitch** [Mach-34/the-word#11]
I'm getting a `fetch` is not defined from [here](https://github.com/Mach-34/the-word/blob/main/cli/src/cli.ts#L130).

Installed with `npm i -g @the-word-pse/cli`

After running getting this:

```
ReferenceError: fetch is not defined
    at whisper (file:///opt/homebrew/lib/node_modules/@the-word-pse/cli/dest/cli.js:230:17)
    at async main (file:///opt/homebrew/lib/node_modules/@the-word-pse/cli/dest/cli.js:81:9)
```

Cool concept for a project

**Comment by vimwitch** [comment]
I've been informed that node 18 added a global `fetch`. Closing because i'm using an unsupported version of node.
